//! The AXI4-Lite bus as two records, one per direction, so an entity that
//! carries the bus declares two ports instead of seventeen. (A single
//! mixed-direction port would need VHDL-2019 mode views; everything else here
//! is VHDL-2008, and tool support for 2019 is unchecked.)

pub const PACKAGE_NAME: &str = "facet_hdl_axil_pkg";

/// Names this package puts in scope for every unit that uses it.
pub const NAMES: &[&str] = &[
    PACKAGE_NAME,
    "axil_m2s_t",
    "axil_s2m_t",
    "axil_m2s_idle",
    "axil_s2m_idle",
];

pub const PACKAGE: &str = r#"-- Generated by facet-hdl. Identical for every boundary.
--
-- Addresses are a full 32 bits. The interconnect hands a slave its local
-- offset, so the high bits are zero; a narrower bus is resized at the edge.
library ieee;
use ieee.std_logic_1164.all;

package facet_hdl_axil_pkg is
  -- Driven by the master (the HPS side).
  type axil_m2s_t is record
    awaddr  : std_logic_vector(31 downto 0);
    awvalid : std_logic;
    wdata   : std_logic_vector(31 downto 0);
    wstrb   : std_logic_vector(3 downto 0);
    wvalid  : std_logic;
    bready  : std_logic;
    araddr  : std_logic_vector(31 downto 0);
    arvalid : std_logic;
    rready  : std_logic;
  end record;

  -- Driven by the slave (the fabric side).
  type axil_s2m_t is record
    awready : std_logic;
    wready  : std_logic;
    bresp   : std_logic_vector(1 downto 0);
    bvalid  : std_logic;
    arready : std_logic;
    rdata   : std_logic_vector(31 downto 0);
    rresp   : std_logic_vector(1 downto 0);
    rvalid  : std_logic;
  end record;

  constant axil_m2s_idle : axil_m2s_t := (
    awaddr => (others => '0'), awvalid => '0', wdata => (others => '0'), wstrb => "1111",
    wvalid => '0', bready => '0', araddr => (others => '0'), arvalid => '0', rready => '0');
  constant axil_s2m_idle : axil_s2m_t := (
    awready => '0', wready => '0', bresp => "00", bvalid => '0',
    arready => '0', rdata => (others => '0'), rresp => "00", rvalid => '0');
end package;
"#;
